# Generated by Django 3.2.13 on 2024-01-16 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SNSTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=50, unique=True)),
                ('faceImg', models.CharField(blank=True, default='', max_length=255)),
                ('accountName', models.CharField(blank=True, default='', max_length=50)),
                ('profile', models.CharField(blank=True, default='', max_length=100)),
                ('snsTree_Data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineBusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=50, unique=True)),
                ('faceImg', models.URLField(blank=True, default='')),
                ('realName', models.CharField(blank=True, default='', max_length=50)),
                ('profile', models.CharField(blank=True, default='', max_length=100)),
                ('companyName', models.CharField(blank=True, default='', max_length=100)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=50)),
                ('mobilePhoneNumber', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('onlineCard_Data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
